steps:
  - name: vorakl/alpine-pelican 
    entrypoint: "/workspace/publish.sh"

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./output/", "gs://www.stevelle.me"]

