steps:
  - name: vorakl/alpine-pelican 
    args: ["pelican-themes", "-i", "/workspace/themes/nest", "&", "pelican", "/workspace/content", "-o", "/workspace/output", "-s", "publishconf.py"]

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./output/", "gs://www.stevelle.me"]

