---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - role: caddy-ansible
      caddy_systemd_network_dependency: false
      caddy_config: |
        stevelle.me, www.stevelle.me, www1.stevelle.me {
          gzip
          tls webmaster@stevelle.me
          root /var/www/site
          log / stdout "{combined}"
          status 404 /.git
          header / {
            # Enable HTTP Strict Transport Security (HSTS) to force clients to always
            # connect via HTTPS (do not use if only testing)
            Strict-Transport-Security "max-age=31536000;"
            # Enable cross-site filter (XSS) and tell browser to block
            # detected attacks
            X-XSS-Protection "1; mode=block"
            # Prevent some browsers from MIME-sniffing a response
            # away from the declared Content-Type
            X-Content-Type-Options "nosniff"
            # Disallow the site to be rendered within a
            # frame (clickjacking protection)
            X-Frame-Options "DENY"
          }
        }
