---

- name: Update site content
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure Git is available
      apt: state=present name=git-core

    - name: Update local checkout
      git:
        repo: https://github.com/stevelle/stevelle.me
        clone: yes
        dest: /var/www/site
        update: yes
        version: deploy
        force: yes
        depth: 1

