---
- name: Secure a new host
  remote_user: ubuntu
  become: yes
  become_method: sudo  
  hosts: all
  tasks:
    - name: Install packages
      apt: state=latest name="{{ item }}"
      with_items:
        - fail2ban
        - unattended-upgrades

    - name: Secure root account 
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PermitRootLogin'
        line='PermitRootLogin no'
      notify:
        - Restart sshd

    - name: Forbit password auth
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line='PasswordAuthentication no' 
      notify:   
        - Restart sshd

    - name: Disallow DNS lookups by sshd
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^UseDNS'
        line='UseDNS no' 
      notify:   
        - Restart sshd

    - name: Disallow X11Forwarding
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^X11Forwarding'
        line='X11Forwarding no'
      notify:   
        - Restart sshd

    - name: Enable TCPKeepAlive
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='TCPKeepAlive'
        line='TCPKeepAlive yes'
      notify:   
        - Restart sshd

  handlers:
    - name: Restart sshd
      service: name=ssh state=restarted

